// src/components/task/task.tsx
import React, { FC, useContext, useState } from "react";
import classNames from "classnames";
import StyledTask from "./task.style";
import Card from "components/card";
import Checkbox from "components/checkbox";
import TrashIcon from "./trash.icon";
import { AppContext } from "./../../context";
import PopupMenu from "components/popupMenu";
import Button from "components/button";

interface Props {
  task: Task;
}

const Task: FC<Props> = ({ task }) => {
  const { updateTasksList } = useContext(AppContext);
  const [isDeleting, setDeleting] = useState<boolean>(false);
  const classes: { task: string; taskType: string } = {
    task: classNames("task", { done: task.done }),
    taskType: classNames("task-type", task.type),
  };
  return (
    <StyledTask className={classes.task}>
      <Card className="task-card">
        <div className="task-content">
          <span className={classes.taskType} />
          <span>{task.title}</span>
        </div>
        <div className="task-controls">
          <button className="remove-btn" onClick={() => setDeleting(true)}>
            <TrashIcon />
          </button>
          {isDeleting && (
            <PopupMenu
              title={`Deleting ${task.type}`}
              actionButtons={
                <>
                  <Button onClick={() => setDeleting(false)}>Cancel</Button>
                  <Button danger onClick={() => updateTasksList({ type: "remove", taskID: task.id })}>
                    Delete
                  </Button>
                </>
              }
              onClose={() => setDeleting(false)}
            >
              You are about to delete this {task.type}, are you sure?
            </PopupMenu>
          )}
          <Checkbox
            onChange={(isChecked) => updateTasksList({ type: "check", taskID: task.id, isChecked })}
            checked={task.done}
          />
        </div>
      </Card>
    </StyledTask>
  );
};

export default Task;

// src/components/task/task.vue
<template>
  <div :class="['task', task.done ? 'done' : '']">
    <Card class="task-card">
      <div class="task-content">
        <span :class="['task-type', task.type]" />
        <span>{{ task.title }}</span>
      </div>
      <div class="task-controls">
        <button class="remove-btn" @click="setDeleting(true)">
          <TrashIcon />
        </button>

        <PopupMenu v-if="isDeleting" :title="`Deleting ${task.type}`" @onClose="setDeleting(false)">
          You are about to delete this {{ task.type }}, are you sure?
          <template v-slot:actionButtons>
            <Button @onClick="setDeleting(false)">Cancel</Button>
            <Button danger @onClick="handleTaskDelete(task)">Delete</Button>
          </template>
        </PopupMenu>

        <Checkbox :checked="task.done" @onChange="(isChecked) => handleTaskCheck(task, isChecked)" />
      </div>
    </Card>
  </div>
</template>

<script>
import Card from "./../card";
import Checkbox from "./../checkbox";
import PopupMenu from "./../popupMenu";
import Button from "./../button";
import TrashIcon from "./trash.icon";

export default {
  name: "Task",
  data() {
    return { isDeleting: false };
  },
  props: {
    task: Object,
    onCheck: Function,
    tasksReducer: Function,
  },
  components: {
    Card,
    TrashIcon,
    Button,
    PopupMenu,
    Checkbox,
  },
  methods: {
    setDeleting(isDeleting) {
      this.isDeleting = isDeleting;
    },
    handleTaskDelete(task) {
      this.tasksReducer({ type: "remove", taskID: task.id });
    },
    handleTaskCheck(task, isChecked) {
      this.tasksReducer({ type: "check", taskID: task.id, isChecked });
    },
  },
};
</script>

<style scoped lang="scss">
@import "./task.style";
</style>
