// src/components/createTaskMenu/createTaskMenu.vue
<template>
  <div>
    <form @submit="handleCreate">
      <PopupMenu :title="`Create a new ${creating}`" @onClose="setCreating(null)">
        <TextInput
          :onChange="handleLabelChange"
          required
          placeholder="e.g. Go to gym"
          name="task-label"
          :label="`${creating} title`"
          :error="error"
        />
        <span v-if="error" class="error">{{ error }}</span>
        <template v-slot:actionButtons>
          <Button @onClick="setCreating(null)">Cancel</Button>
          <Button @onClick="handleCreate">Create</Button>
        </template>
      </PopupMenu>
    </form>
  </div>
</template>

<script>
import PopupMenu from "./../popupMenu";
import Button from "./../button";
import TextInput from "./../textInput";
import { getRandomID } from "./../../helpers";

export default {
  name: "CreateTask",
  data() {
    return {
      taskTitle: "",
      error: false,
    };
  },
  methods: {
    setError(error) {
      this.error = error;
    },
    setTaskTitle(e) {
      const { target } = e;
      this.taskTitle = target.value;
    },
    handleCreate() {
      console.log({ taskTitle: this.taskTitle });
      if (this.taskTitle) {
        this.tasksReducer({ type: "add", task: { id: getRandomID(), title: this.taskTitle, type: this.creating } });
        this.setCreating(null);
      } else {
        this.error = `Please include ${this.creating} title!`;
      }
    },
    handleLabelChange(e) {
      this.setError(null);
      this.setTaskTitle(e);
    },
  },
  components: {
    PopupMenu,
    Button,
    TextInput,
  },
  props: {
    creating: String,
    setCreating: Function,
    tasksReducer: Function,
  },
};
</script>

<style scoped lang="scss">
@import "./createTaskMenu.style";
</style>

// src/components/createTaskMenu/createTaskMenu.jsx
import React, { useState, useRef, useEffect } from "react";
import { useDispatch } from "react-redux";
import propTypes from "prop-types";
import PopupMenu from "components/popupMenu";
import Button from "components/button";
import TextInput from "components/textInput";
import StyledCreateTaskMenu from "./createTaskMenu.style";
import { getRandomID } from "./../../helpers";

const CreateTask = ({ creating, setCreating }) => {
  const dispatch = useDispatch();
  const [taskTitle, setTaskTitle] = useState("");
  const [error, setError] = useState(null);
  const taskTitleRef = useRef(null);

  useEffect(() => {
    setTimeout(() => {
      taskTitleRef.current?.focus();
    }, 500);
  }, []);

  const handleCreate = () => {
    if (taskTitle) {
      dispatch({ type: "add", task: { id: getRandomID(), title: taskTitle, type: creating } });
      setCreating(null);
    } else {
      setError(`Please include ${creating} title!`);
    }
  };

  return (
    <StyledCreateTaskMenu>
      <form onSubmit={handleCreate}>
        <PopupMenu
          title={`Create a new ${creating}`}
          onClose={() => setCreating(null)}
          actionButtons={
            <>
              <Button onClick={() => setCreating(null)}>Cancel</Button>
              <Button onClick={handleCreate}>Create</Button>
            </>
          }
        >
          <TextInput
            onChange={({ target }) => {
              setError(null);
              setTaskTitle(target.value);
            }}
            required
            placeholder="e.g. Go to gym"
            name="task-label"
            label={`${creating} title`}
            error={error}
            ref={taskTitleRef}
          />
          {error && <span className="error">{error}</span>}
        </PopupMenu>
      </form>
    </StyledCreateTaskMenu>
  );
};

CreateTask.propTypes = {
  creating: propTypes.string,
  setCreating: propTypes.func,
};

export default CreateTask;
