// src/components/addMenu/addMenu.tsx
import React, { FC } from "react";
import StyledAddMenu from "./addMenu.style";

interface Props {
  setClicked: (isClicked: boolean) => void;
  setCreating: (creating: "task" | "event") => void;
}

const AddMenu: FC<Props> = ({ setClicked, setCreating }) => {
  return (
    <StyledAddMenu>
      <ul>
        <li
          onClick={() => {
            setClicked(false);
            setCreating("task");
          }}
        >
          Add a new Task
        </li>
        <li
          onClick={() => {
            setClicked(false);
            setCreating("event");
          }}
        >
          Add a new Event
        </li>
      </ul>
      <div className="add-menu-blocker" onClick={() => setClicked(false)} />
    </StyledAddMenu>
  );
};

export default AddMenu;

// src/components/addMenu/addMenu.vue
<template>
  <div className="add-task-menu">
    <ul>
      <li
        @click="
          setClicked(false);
          setCreating('task');
        "
      >
        Add a new Task
      </li>
      <li
        @click="
          setClicked(false);
          setCreating('event');
        "
      >
        Add a new Event
      </li>
    </ul>
    <div className="add-menu-blocker" @click="setClicked(false)" />
  </div>
</template>

<script>
export default {
  name: "AddMenu",
  props: {
    setClicked: Function,
    setCreating: Function,
  },
};
</script>

<style scoped lang="scss">
@import "./addMenu.style";
</style>
