// src/components/addMenu/addMenu.jsx
import React from "react";
import propTypes from "prop-types";
import StyledAddMenu from "./addMenu.style";

const AddMenu = ({ setClicked, setCreating }) => {
  return (
    <StyledAddMenu>
      <ul>
        <li
          onClick={() => {
            setClicked(false);
            setCreating("task");
          }}
        >
          Add Task
        </li>
        <li
          onClick={() => {
            setClicked(false);
            setCreating("event");
          }}
        >
          Add Event
        </li>
      </ul>
      <div className="add-menu-blocker" onClick={() => setClicked(false)} />
    </StyledAddMenu>
  );
};

AddMenu.propTypes = {
  setClicked: propTypes.func,
  setCreating: propTypes.func
};

export default AddMenu;

// src/components/addMenu/addMenu.vue
<template>
  <div className="add-task-menu">
    <ul>
      <li
        @click="
          setClicked(false);
          setCreating('task');
        "
      >
        Add a new Task
      </li>
      <li
        @click="
          setClicked(false);
          setCreating('event');
        "
      >
        Add a new Event
      </li>
    </ul>
    <div className="add-menu-blocker" @click="setClicked(false)" />
  </div>
</template>

<script>
export default {
  name: "AddMenu",
  props: {
    setClicked: Function,
    setCreating: Function,
  },
};
</script>

<style scoped lang="scss">
@import "./addMenu.style";
</style>
