// src/components/popupMenu/popupMenu.tsx
import React, { FC, ReactElement } from "react";
import StyledPopupMenu from "./popupMenu.style";

interface Props {
  title: string;
  actionButtons: ReactElement;
  onClose: () => void;
}

const PopupMenu: FC<Props> = ({ title, actionButtons, onClose, children }) => {
  return (
    <StyledPopupMenu>
      <div className="popup-menu">
        <div className="popup-title">{title}</div>
        {children}
        <div className="action-buttons">{actionButtons}</div>
      </div>
      <div className="popup-blocker" onClick={onClose} />
    </StyledPopupMenu>
  );
};

export default PopupMenu;

// src/components/popupMenu/popupMenu.vue
<template>
  <div className="popup-menu">
    <div class="popup-title">{{ title }}</div>
    <slot />
    <div class="action-buttons"><slot name="actionButtons" /></div>
  </div>
  <div class="popup-blocker" @click="onClose" />
</template>

<script>
export default {
  name: "PopupMenu",
  props: {
    title: String,
  },
  methods: {
    onClose() {
      this.$emit("on-close");
    },
  },
};
</script>

<style lang="scss">
@import "./popupMenu.style";
</style>
