// src/components/popupMenu/popupMenu.jsx
import React from "react";
import propTypes from "prop-types";
import StyledPopupMenu from "./popupMenu.style";

const PopupMenu = ({ title, children, actionButtons, onClose }) => {
  return (
    <StyledPopupMenu>
      <div className="popup-menu">
        <div className="popup-title">{title}</div>
        {children}
        <div className="action-buttons">{actionButtons}</div>
      </div>
      <div className="popup-blocker" onClick={() => onClose()} />
    </StyledPopupMenu>
  );
};

PopupMenu.propTypes = {
  title: propTypes.string,
  actionButtons: propTypes.any,
  onClose: propTypes.func,
  children: propTypes.any
};

export default PopupMenu;

// src/components/popupMenu/popupMenu.vue
<template>
  <div className="popup-menu">
    <div class="popup-title">{{ title }}</div>
    <slot />
    <div class="action-buttons"><slot name="actionButtons" /></div>
  </div>
  <div class="popup-blocker" @click="onClose" />
</template>

<script>
export default {
  name: "PopupMenu",
  props: {
    title: String,
  },
  methods: {
    onClose() {
      this.$emit("on-close");
    },
  },
};
</script>

<style lang="scss">
@import "./popupMenu.style";
</style>
