// src/components/header/header.jsx
import React from "react";
import useStore from "./../../store";
import StyledHeader from "./header.style";
import Toggle from "components/toggle";

const Header = () => {
  const showDoneTasks = useStore((state) => state.showDoneTasks);
  const setDoneTasksVisibility = useStore((state) => state.setDoneTasksVisibility);

  return (
    <StyledHeader>
      <a href="https://github.com/MustafaFaris" target="_blank" rel="noreferrer">
        <span className="user">
          <span>M</span>
        </span>
      </a>
      <div className="page-title">
        My Tasks
        <span className="toggle-done">
          Show done tasks <Toggle onChange={setDoneTasksVisibility} toggled={showDoneTasks} />
        </span>
      </div>
    </StyledHeader>
  );
};

export default Header;

// src/components/header/header.vue
<template>
  <header>
    <a href="https://github.com/MustafaFaris" target="_blank" rel="noreferrer">
      <span class="user">
        <span>M</span>
      </span>
    </a>
    <div class="page-title">
      My Tasks
      <span class="toggle-done">
        Show done tasks <Toggle :toggled="showDoneTasks" :onChange="handleTaskVisiblityToggle" />
      </span>
    </div>
  </header>
</template>

<script>
import Toggle from "./../toggle";

export default {
  name: "Header",
  methods: {
    handleTaskVisiblityToggle(isVisible) {
      this.tasksReducer({ type: "setDoneTasksVisibility", isVisible });
    },
  },
  components: {
    Toggle,
  },
  props: {
    showDoneTasks: Boolean,
    tasksReducer: Function,
  },
};
</script>

<style scoped lang="scss">
@import "./header.style";
</style>
