// src/components/checkbox/checkbox.tsx
import React, { FC, useState } from "react";
import classNames from "classnames";
import StyledCheckbox from "./checkbox.style";
import CheckIcon from "./check.icon";

interface Props {
  checked?: boolean;
  defaultChecked?: boolean;
  onChange: (isChecked: boolean) => void;
}

const Checkbox: FC<Props> = ({ checked, defaultChecked, onChange }) => {
  const [isChecked, setChecked] = useState<boolean>(checked || defaultChecked || false);
  const onCheckChange = () => {
    setChecked(!isChecked);
    if (onChange) onChange(!isChecked);
  };
  const classes = classNames("checkbox", { checked: checked || isChecked });

  return (
    <StyledCheckbox className={classes} onClick={() => onCheckChange()}>
      <CheckIcon />
    </StyledCheckbox>
  );
};

export default Checkbox;

// src/components/checkbox/checkbox.vue
<template>
  <span :class="['checkbox', isChecked ? 'checked' : '']" @click="onCheckChange">
    <CheckIcon />
  </span>
</template>

<script>
import CheckIcon from "./check.icon";
export default {
  name: "Checkbox",
  data() {
    return {
      isChecked: this.checked !== undefined ? this.checked : false,
    };
  },
  methods: {
    onCheckChange() {
      this.isChecked = !this.isChecked;
      this.$emit("onChange", this.isChecked);
    },
  },
  components: {
    CheckIcon,
  },
  props: {
    checked: Boolean,
  },
};
</script>

<style scoped lang="scss">
@import "./checkbox.style";
</style>
