// src/components/addTask/addTask.tsx
import React, { FC, useState } from "react";
import classNames from "classnames";
import StyledAddTask from "./addTask.style";
import AddMenu from "components/addMenu";
import CreateTaskMenu from "components/createTaskMenu";
import PlusIcon from "./plus.icon";

const AddTask: FC = () => {
  const [isClicked, setClicked] = useState<boolean>(false);
  const [creating, setCreating] = useState<string | null>(null);

  const classes: string = classNames("add-task-button", { isClicked });

  return (
    <StyledAddTask>
      <button className={classes} onClick={() => setClicked(!isClicked)}>
        <PlusIcon />
      </button>
      {isClicked && <AddMenu setClicked={setClicked} setCreating={setCreating} />}
      {creating && <CreateTaskMenu creating={creating} setCreating={setCreating} />}
    </StyledAddTask>
  );
};

export default AddTask;

// src/components/addTask/addTask.vue
<template>
  <button :class="['add-task-button', isClicked ? 'isClicked' : '']" @click="setClicked(!isClicked)">
    <PlusIcon />
  </button>
  <AddMenu v-if="isClicked" :setClicked="setClicked" :setCreating="setCreating" />
  <CreateTaskMenu v-if="creating" :creating="creating" :setCreating="setCreating" :tasksReducer="tasksReducer" />
</template>

<script>
import AddMenu from "./../addMenu";
import CreateTaskMenu from "./../createTaskMenu";
import PlusIcon from "./plus.icon";

export default {
  name: "AddTask",
  data() {
    return {
      isClicked: false,
      creating: null,
    };
  },
  methods: {
    setClicked(isClicked) {
      this.isClicked = isClicked;
    },
    setCreating(type) {
      this.creating = type;
    },
  },
  components: {
    AddMenu,
    CreateTaskMenu,
    PlusIcon,
  },
  props: {
    tasksReducer: Function,
  },
};
</script>

<style scoped lang="scss">
@import "./addTask.style";
</style>
