// src/components/toggle/toggle.tsx
import React, { FC, useState } from "react";
import classNames from "classnames";
import StyledToggle from "./toggle.style";

interface Props {
  toggled?: boolean;
  defaultChecked?: boolean;
  onChange: (isToggled: boolean) => void;
}

const Toggle: FC<Props> = ({ toggled, defaultChecked, onChange }) => {
  const [isToggled, setToggled] = useState(toggled || defaultChecked);
  const onToggleChange = () => {
    setToggled(!isToggled);
    if (onChange) {
      onChange(!isToggled);
    }
  };
  const classes = classNames("toggle", { toggled: isToggled });

  return <StyledToggle className={classes} onClick={() => onToggleChange()} />;
};

export default Toggle;

// src/components/toggle/toggle.vue
<template>
  <div :class="[isToggled ? 'toggled' : '', 'toggle']" @click="onToggleChange" />
</template>

<script>
export default {
  name: "Toggle",
  props: {
    defaultChecked: Boolean,
    toggled: Boolean,
    onChange: Function,
  },
  data() {
    return {
      isToggled: this.toggled !== undefined ? this.toggled : "false",
    };
  },
  methods: {
    onToggleChange() {
      this.isToggled = !this.isToggled;
      if (this.onChange) {
        this.onChange(this.toggled !== undefined ? !this.toggled : !this.isToggled);
      }
    },
  },
};
</script>

<style scoped lang="scss">
@import "./toggle.style";
</style>
