// src/components/toggle/toggle.vue
<template>
  <div :class="[isToggled ? 'toggled' : '', 'toggle']" @click="onToggleChange" />
</template>

<script>
export default {
  name: "Toggle",
  props: {
    defaultChecked: Boolean,
    toggled: Boolean,
    onChange: Function,
  },
  data() {
    return {
      isToggled: this.toggled !== undefined ? this.toggled : "false",
    };
  },
  methods: {
    onToggleChange() {
      this.isToggled = !this.isToggled;
      if (this.onChange) {
        this.onChange(this.toggled !== undefined ? !this.toggled : !this.isToggled);
      }
    },
  },
};
</script>

<style scoped lang="scss">
@import "./toggle.style";
</style>

// src/components/toggle/toggle.jsx
import React, { useState } from "react";
import classNames from "classnames";
import propTypes from "prop-types";
import StyledToggle from "./toggle.style";

const Toggle = ({ toggled, defaultChecked, onChange = () => {} }) => {
  const [isToggled, setToggled] = useState(toggled || defaultChecked);
  const onToggleChange = () => {
    setToggled(!isToggled);
    onChange(!isToggled);
  };
  const classes = classNames("toggle", { toggled: isToggled });

  return <StyledToggle className={classes} onClick={() => onToggleChange()} />;
};

Toggle.propTypes = {
  defaultChecked: propTypes.bool,
  toggled: propTypes.bool,
  onChange: propTypes.func
};

export default Toggle;
