// src/components/tasksView/tasksView.tsx
import React, { FC, useContext } from "react";
import { AppContext } from "./../../context";
import StyledTasksView from "./tasksView.style";
import Task from "components/task";

const TasksView: FC = () => {
  const { tasksList, showDoneTasks } = useContext(AppContext);
  return (
    <StyledTasksView className="tasks-view">
      {tasksList.length ? (
        tasksList
          .filter((task: Task): Task[] => !task.done || showDoneTasks)
          .map((task: Task) => <Task key={"task-" + task.id} task={task} />)
      ) : (
        <p className="no-tasks">You don&apos;t have any tasks</p>
      )}
    </StyledTasksView>
  );
};

export default TasksView;

// src/components/tasksView/tasksView.vue
<template>
  <div class="tasks-view">
    <template v-if="tasks.length">
      <template :key="task.id" v-for="task in tasks">
        <Task v-if="!task.done || showDoneTasks" :task="task" :tasksReducer="tasksReducer" />
      </template>
    </template>
    <template v-else><p className="no-tasks">You don&apos;t have any tasks</p></template>
  </div>
</template>

<script>
import Task from "./../task";
export default {
  name: "TasksView",
  components: {
    Task,
  },
  props: {
    tasks: {
      type: Array,
      default: function () {
        return [];
      },
    },
    tasksReducer: Function,
    showDoneTasks: Boolean,
  },
  methods: {
    filterDoneTasks(tasks, shouldFilter) {
      return tasks.filter((task) => !task.done || shouldFilter);
    },
  },
};
</script>

<style scoped lang="scss">
@import "./tasksView.style";
</style>
