// src/components/tasksView/tasksView.vue
<template>
  <div class="tasks-view">
    <template v-if="tasks.length">
      <template :key="task.id" v-for="task in tasks">
        <Task v-if="!task.done || showDoneTasks" :task="task" :tasksReducer="tasksReducer" />
      </template>
    </template>
    <template v-else><p className="no-tasks">You don&apos;t have any tasks</p></template>
  </div>
</template>

<script>
import Task from "./../task";
export default {
  name: "TasksView",
  components: {
    Task,
  },
  props: {
    tasks: {
      type: Array,
      default: function () {
        return [];
      },
    },
    tasksReducer: Function,
    showDoneTasks: Boolean,
  },
  methods: {
    filterDoneTasks(tasks, shouldFilter) {
      return tasks.filter((task) => !task.done || shouldFilter);
    },
  },
};
</script>

<style scoped lang="scss">
@import "./tasksView.style";
</style>

// src/components/tasksView/tasksView.jsx
import React from "react";
import useStore from "./../../store";
import StyledTasksView from "./tasksView.style";
import Task from "components/task";

const TasksView = () => {
  const tasksList = useStore((state) => state.tasksList);
  const showDoneTasks = useStore((state) => state.showDoneTasks);

  return (
    <StyledTasksView className="tasks-view">
      {tasksList.length ? (
        tasksList
          .filter((task) => !task.done || showDoneTasks)
          .map((task) => <Task key={"task-" + task.id} task={task} />)
      ) : (
        <p className="no-tasks">You don&apos;t have any tasks</p>
      )}
    </StyledTasksView>
  );
};

export default TasksView;
